// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsQnPQMhJSXauMo1VUOEeTDiRviaj50Z0',
    appId: '1:253239783033:web:e8da99b44eb11c8e67eea8',
    messagingSenderId: '253239783033',
    projectId: 'aiden-14970',
    authDomain: 'aiden-14970.firebaseapp.com',
    storageBucket: 'aiden-14970.appspot.com',
    measurementId: 'G-6S8D6X30LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFOqmgQt2jSFjQqdHmsry6bPYuP5wuPwE',
    appId: '1:253239783033:android:57cb480fe57a7ed867eea8',
    messagingSenderId: '253239783033',
    projectId: 'aiden-14970',
    storageBucket: 'aiden-14970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLo7_ofsjHfuIldP_qiOdeBF4gms2vA8',
    appId: '1:253239783033:ios:befb9e360fdf958e67eea8',
    messagingSenderId: '253239783033',
    projectId: 'aiden-14970',
    storageBucket: 'aiden-14970.appspot.com',
    iosBundleId: 'com.example.aiden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLo7_ofsjHfuIldP_qiOdeBF4gms2vA8',
    appId: '1:253239783033:ios:e8d91b275693ca0e67eea8',
    messagingSenderId: '253239783033',
    projectId: 'aiden-14970',
    storageBucket: 'aiden-14970.appspot.com',
    iosBundleId: 'com.example.aiden.RunnerTests',
  );
}
